### ISSUE TITLE
Management command to delete history

### ISSUE THREAD

**Issue by jacklinke** [fsbraun/django-automations#12]
**Is your feature request related to a problem? Please describe.**

AutomationModel has a delete_history class method, but no associated management command, which would be convenient.

**Describe the solution you'd like**

`>>> python manage.py automation_delete_history.py`
or

`>>> python manage.py automation_delete_history.py 14`

**Additional context**

If this is something that you think would add value, I'll submit a PR. Code, docs, and tests are ready to go, but I have not submitted yet because I'm hoping we can get #11 completed first (since tests moved to a `tests` directory, conflicting with master branch)

**Comment by fsbraun** [comment]
This actually is on my to do list! Of course, you are invited. It's a practical thing also for privacy considerations - automations might contain private data.
