### ISSUE TITLE
Missing template

### ISSUE THREAD

**Issue by rolandf** [fsbraun/django-automations#26]
I added automations and cms_automations in INSTALLED_APPS.

Then when trying to migrate I got the following exception.

django.core.exceptions.ImproperlyConfigured: CMS Plugins must define a render template, a get_render_template method or set render_plugin=False: <class 'automations.cms_automations.cms_plugins.AutomationTaskList'>

I'm using django 3.2.15 and dcms 3.11.

**Comment by fsbraun** [comment]
This looks like that the plugin is missing `get_render_template` and the template is assigned in the `render` method which is bad practice.

**Comment by fsbraun** [comment]
Fixed by https://github.com/fsbraun/django-automations/commit/5b977cf6fdd0e59cec45968e9895bc015c1e28ee. You'd need to install from the repo to test: 

    pip install git+https://github.com/fsbraun/django-automation@master#egg=django-automation

I am not sure why this did not pop up earlier though.
