### ISSUE TITLE
Installing django-automations in a project with a custom User model results in error

### ISSUE THREAD

**Issue by jacklinke** [fsbraun/django-automations#3]
**Describe the bug**
Code currently references the auth.User model, but many (most) projects use a custom User model set in settings.AUTH_USER_MODEL, as recommended in django docs. The current code results in errors for any project with custom User installing django-automations.

**To Reproduce**
1. Add a custom User model to project
2. Try to install django-automations
3. Receive error that a custom User model is referenced in settings, but django-automations refers to auth.User

**Expected behavior**
Seamless installation regardless of User model.

**Comment by fsbraun** [comment]
@jacklinke Thanks for the hint and PR!
