### ISSUE TITLE
Asking users to `makemigrations` locally can cause future problems if project pushes new migrations

### ISSUE THREAD

**Issue by jacklinke** [fsbraun/django-automations#4]
**Describe the bug**
The docs currently tell users to run `makemigrations`, and then `migrate`. This causes migration files to be written to a user's package source files, which are not intended to be updated locally. If django-automations pushes future migrations, they will conflict with users' local migrations, breaking projects.

**Comment by fsbraun** [comment]
Yes, I agree! Thanks for pointing out!
