### ISSUE TITLE
Code formatting and consistency

### ISSUE THREAD

**Issue by jacklinke** [fsbraun/django-automations#5]
@fsbraun I really love this project, and it looks like it has great potential!

There is some lack of consistency in indentation, imports, use of f-strings where not needed, etc. Would a PR that addresses all of this be appreciated?

My recommendations would be to use the following tools:

- isort

In several places imports can be optimized and cleaned up. For instance, cms_plugins.py imports `models`, `flow`, and `views` on separate lines, but they can be combined to a single import.

- black

black has become the defacto standard in the python world. We would need to use the [# fmt: on/off](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#code-style) comments to keep the visual style (multiple spaces) you use for demonstrating the workflows, which is very effective.

- flake8

There are some minor issues such as f-strings used with no variables, and a local variable that is assigned-to, but never used. While these don't cause any problems, they could be cleaned up.

- djhtml

Provides a nice consistent indentation style for django templates.

---

I would love your thoughts on this. If this all sounds good, please let me know and I will submit a PR to implement these changes.

**Comment by fsbraun** [comment]
I very much appreciate the idea! I have made some adjustments but have not automated the process. I would appreciate a PR very much..

**Comment by jacklinke** [comment]
Looks like you added the pre-commit hooks before I was able to get around to it :smile: Nice!

Should we consider c1b8894 to fully close this issue out?

**Comment by fsbraun** [comment]
Let me know if you come across issues with the pre-commits. In the mean time: Closed with commit c1b8894.
